# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b54dc49853e24462c85855cfc8216535a8a27876a30034010e2141218fe0d46efc66a04fd1fc4cda42beba27032b8c46d5313fe702ee90287e8d35f6444895a

test:
  secret_key_base: 42ec58cd17d48f98231c747cc6fe891610bd129b9b24203594d8c75258edbbb76a1eee1ccdea2db34c57d92303fbf7e13f9e39bdde796401b2a74380a60ed4ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
